global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:9187"]

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:9363"]

  - job_name: "kafka"
    static_configs:
      - targets: ["redpanda:9644"]

  - job_name: "minio"
    static_configs:
      - targets: ["wotr_dbms_platform-minio-1:9000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
